baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hallo"

[Author]
name = "Sungwon Lee"

[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/ssowonny"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:ssowonny@gmail.com"
    [params.colors]
        background = "#ec7a1c"
        foreground = "#edf7ff"
        hover = "#ffba82"
